[Add] Navigation, Network API 연결
MalibinStudy/SimpleGithubApp pull request #8
Opened 2020-06-08 14:24 UTC by seunghee63

죄송합니당.. UI 짜기가 너무 귀찮아서 네트워크 연결을 먼저 해 버렸습니다.. 내일 마저 완성하도록 할게요!

* retrofit 통신은 CallBack 방식으로 구현하였습니다.
* 서버 retrofit 객체를 구현하는 코드를 항상 Application Class 를 상속받아 구현했었는데, 왜 그렇게 구현했었는지..에 대한 궁금증이 생겼습니다. Application Class 의 특징 때문인가? (가장 먼저 실행된다는 특성상 onCreate에 retrofit 객체 생성을 하는 것 과 같은?!?!) 싶다가도 Application Class를 상속 받는 형태가 아닌 상태로 구현을 해도 충분히 잘 작동을해서 어떤 방식이 더 나은 방식인지.. 궁금합니당!

2020-06-08 16:26 UTC, malibinYun requested changes
자바 컨벤션을 지키도록 합시다!
https://kotlinlang.org/docs/reference/coding-conventions.html
https://google.github.io/styleguide/javaguide.html

이름에 고민을 많이 하는게 좋아! 나는 진짜 이름으로만 고민 개많이하거든..

앱 실행을 안해봐서 뭔가 되는지 안되는지 잘 모르겟넼ㅋㅋㅋㅋ 한번 고쳐봅시다!

2020-06-08 16:26 UTC, malibinYun commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Actor.kt
> +data class Actor(
Actor는 뭔가 행위를 할거같은 애 또는 배우명? 이럴것같아. 나라면 GithubAccount 등 더 구체적인 네이밍을 선택할거같아.
 SerializedName는 완벽하게 Gson에 의존하니까 조심해서 써야하구(만약 Json Parser를 Gson이 아닌 다른걸 쓰게 된다면 전부 싹 갈아치워야겠지?)
 SerializedName 여기서 Key값을 가져왔으니 변수명 자체는 내가 제대로 알아먹을 수 있는 구체적인 변수명을 쓰는게 낫다고봐.
 또, 보여주지 않을 데이터를 굳이 전부 가져와서 쓰는건 가독성을 낮추고 낭비라고 생각해.
 컨버터를 쓰더라도 불필요한건 없애는게 좋아보여.

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/GetFeedResponse.kt
> +data class GetFeedResponse(
클래스명만 봐서 이놈이 어떤놈의 응답바디인지 잘 모르겠어. 더 구체적인 네이밍이 필요해보여

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/GetStarResponse.kt
> +data class GetStarResponse(
이것도 마찬가지

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Org.kt
> +data class Org(
이것도..

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Org.kt
> +data class Org(
축약어는 좋지않습니다

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Owner.kt
> +data class Owner(
음.. 어떤 오너를 칭하는걸까? 레파지토리? 오가니제이션? 계정? 더 구체적인 네이밍이 필요해

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/OwnerX.kt
> +data class OwnerX(
Owner class랑 딱 두개만 놓고 비교해보면 첨보는 사람입장에서는 절대 어떤 차이가 있는지 모를거라고 생각해.

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Permissions.kt
> +data class Permissions(
어떤 권한을 말하는건지 모르겠어. 더 구체적인 네이밍!

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Repo.kt
> +data class Repo(
왠만하면 축약어는 안쓰는게 좋아.

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/network/ApiClient.kt
> +object ApiClient{
Application()을 상속받아서 매니페스트에 등록해서 사용하는거는
 매니페스트에 등록된 해당 클래스는 App이 켜지고 딱 한 번만 실행돼. 마치 Acitivity에서 onCreate()가 딱 한 번 실행되는 것 처럼.
 Network 객체는 엄청나게 무겁다고 알려져있어. 그래서 싱글톤으로 구현해야해. 그래서 딱 한번만 객체를 만들어줄 위치가 필요하게되는데,
 Application() 상속받고 매니페스트에 등록한 그 클래스가 딱한번 실행되니, 거기서 메모리에 올리는 작업을 하는거야.
 Java에서는 object라는게 없었고, 구글 문서에서도 Application에다가 초기화하는걸 권장해서 그렇게 굳어진거라 생각해.
 근데 나는 object는 좀 위험한거같아. 구글 예제 코드들도 그렇고 다른 외국인들 코드도 그렇고, 다들 정적팩터리메서드 패턴으로 싱글턴을 구현하거든.
 다른사람들이 프로덕션 코드에 object를 잘 쓰지 않는건 다 이유가 있다고 생각해서 나는 잘 쓰지 않는 키워드야.

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/network/ApiClient.kt
> +    private const val BASE_URL = "https://api.github.com/"
BaseUrl은 만약 파일에 노출시킬거면, 여기보다는 이 Service를 제공해주는 인터페이스에다가
 상수로써 작성해놓는게 좀 더 나아.
 내가 만약 다른 서비스들을 더 이용해. API 한 20개를 쓴다 생각하자. 그럼 여기에만 URL이 엄청 몰릴꺼야.
 그렇다면 클래스의 응집도가 떨어져서 좋지않다고봐. 또, 어떤 Service의 interface가 어떤 url이였는지
 나라면 까먹을거같아.

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/MainActivity.kt
> +    fun setBottomNavigation(){
이 클래스에서만 사용되는 메서드는 꼭 private를 붙여줘. 다른곳에서 접근하지못하게

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +class FeedFragment : Fragment(R.layout.fragment_feed) {
오 프래그먼트 생성자에 layout id를 넘기면 되는건 처음알았어.
 난 개인적으로 좀 주의해서 써야한다고 생각해. 라이프사이클을 생각해보면, 프래그먼트는 뷰가 자주 없어져서
 onCreateView() 이놈이 자주 실행이되는데, 이때를 잘 생각을 해야된다고 생각해.
 View에 리사이클러뷰 어뎁터라던지, 데이터바인딩을 통한 뷰모델 바인딩이라던지, 이런게 다 끊어질거란말이지.
 onCreateView를 오버라이딩 하지 않아도 되는 장점이 있지만, 그렇기에 더 생각을 많이하고 써야한다고 생각해!

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +                Log.e("get feed fail", t.toString())
```suggestion
                Log.e("get feed fail",TextUtils.join("\n", t.stackTrace) )
```
난 이걸로 에러스택 보는게 편하더라고

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +    fun setRecyclerView(){
ListAdapter를 만들었으면 리사이클러뷰에다가 어뎁터를 등록해줘야하는건 똑같아.

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +    private class DiffTool : DiffUtil.ItemCallback<Test>(){
내부 클래스들을 맽 밑에다가 위치시키는게 자바 컨벤션이야

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +    inner class ViewHolder(val binding: ItemFollowersBinding) : RecyclerView.ViewHolder(binding.root) {
```suggestion
    inner class ViewHolder(private val binding: ItemFollowersBinding) : RecyclerView.ViewHolder(binding.root) {
```
여기서만 사용하는 변수는 private를 붙여주는게 좋아

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +    }
```suggestion
    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        val item = getItem(position)
        holder.bind(item) //데이터를 바인딩까지 해줘야해

    }
```

2020-06-08 16:26 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +data class Test(
그냥 스터디때 따라친거엿나? 다른부분 리사이클러뷰 있는부분에 꼭 적용해봐.

2020-06-09 21:04 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +class FeedFragment : Fragment(R.layout.fragment_feed) {
데이터 바인딩 적용 하기 전 임시적으로 ui inflater를 생성자에 넘겨서 했었는데 더 생각 할 필요가 있는 것 같네! 앞으로는 조금 더 유의하도록 할게요~!

a53597e

2020-06-09 21:06 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +    fun setRecyclerView(){
ui 작업 전이라, 스터디 실습할 때 만들어 놓고 리사이클러뷰에 연결을 안 했었어융! 추가했습니다~

29f4a45
c5331e3
a53597e

2020-06-10 09:35 UTC, malibinYun requested changes
data 클래스나 기타 다른것들도 피드백 반영해봅시다!

2020-06-10 09:35 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/util/BindingAdapter.kt
> +@BindingAdapter("android:background_grade")
android: 이걸 써버리면 xml에서 볼때 이게 android에서 기본 제공해주는 attribution이라고 생각할거같아. 이건 기본제공이 아니라서 우리가 커스텀으로 만들어준거잖아?
background_grade 이렇게 쓰고 뷰단에서는 app: 를 붙여줘도돼. 안붙여도되구

2020-06-10 09:35 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +        return inflater.inflate(R.layout.fragment_feed, container, false)
데이터 바인딩으로 고쳐보자!

2020-06-10 09:35 UTC, nightmare73 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +        rv_feed_list.adapter = adapter
레이아웃 매니저는 뷰에서도 박을수잇음 개꿀임
뷰를 코틀린 익스텐션으로 더이상 접근하지말구 배운 데이터바인딩을 사용해보자!

2020-06-29 19:17 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/network/ApiClient.kt
> +    private const val BASE_URL = "https://api.github.com/"
인터페이스에서 BASEURL을 관리하도록 수정하엿슘당~!

b36e4fe

2020-06-29 19:19 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/network/ApiClient.kt
> +object ApiClient{
Application에서 retrofit 객체를 관리 하는 것으로 수정~
매날 복붙해서 쓰던 코드를 고민하며 짜보니 색다르네!

b95337c

2020-06-29 19:20 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/util/BindingAdapter.kt
> +@BindingAdapter("android:background_grade")
app: 으로 수정했어유!

4b749e8

2020-06-29 19:20 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/util/BindingAdapter.kt
> +@BindingAdapter("android:background_grade")
972e296

2020-06-29 19:24 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +    inner class ViewHolder(val binding: ItemFollowersBinding) : RecyclerView.ViewHolder(binding.root) {
스터디때 따라 치던 코드...! ㅋㅋ..ㅠㅠ 새로 적용한 코드에는 모두 적용했습니다~

2020-06-29 19:25 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +    }
마찬가지로! 스터디때 따라 치던 코드...! 새로 적용한 코드에는 모두 적용했습니다~

2020-06-29 19:25 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +data class Test(
마찬가지로! 스터디때 따라 치던 코드...! 새로 적용한 코드에는 모두 적용했습니다~

2020-06-29 19:27 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/TestListAdapter.kt
> +    private class DiffTool : DiffUtil.ItemCallback<Test>(){
처음알았다..! feebd51 적용했어요~
앞으로도 유의하도록 할게유!

2020-06-29 19:29 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/MainActivity.kt
> +    fun setBottomNavigation(){
7076afa
항상 좀 접근제한자를 제멋대로 했던 것 같아 앞으로는 신경써서 할게유!!

2020-06-29 19:44 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +        rv_feed_list.adapter = adapter
6867581

레이아웃 매니저 뷰에서 박는건 뷰모델 적용할때 하겠습니당
지금 하게되면 Activity를 xml에 임폴트 해야 해서 너무 효율성이 떨어진다!

2020-06-29 19:44 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/ui/feed/FeedFragment.kt
> +        return inflater.inflate(R.layout.fragment_feed, container, false)
6867581

2020-06-29 20:01 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Actor.kt
> +data class Actor(
d9d563f

2020-06-29 20:02 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/GetFeedResponse.kt
> +data class GetFeedResponse(
0ec5d18

2020-06-29 20:02 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/GetStarResponse.kt
> +data class GetStarResponse(
0ec5d18

2020-06-29 20:03 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/OwnerX.kt
> +data class OwnerX(
e2b7df4 중복되는 클래스여서 제거했습니닷!

2020-06-29 20:03 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Owner.kt
> +data class Owner(
RepositoryOwner로 수정했어유~

e2b7df4

2020-06-29 20:03 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Org.kt
> +data class Org(
e2b7df4

2020-06-29 20:04 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Permissions.kt
> +data class Permissions(
Repository 접근권한,.!

e2b7df4

2020-06-29 20:04 UTC, seunghee63 commented on myGitApp/app/src/main/java/com/song2/mygitapp/data/Repo.kt
> +data class Repo(
e2b7df4

2020-07-01 17:57 UTC, merged